permissions:
  contents: read
  actions: write
name: Docker Build Cache

on:
  push:
    branches: [develop]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "integrations/**"

jobs:
  build-main-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout IntelOwl
        uses: actions/checkout@v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake images
        uses: docker/bake-action@v6
        with:
          source: .
          files: docker/docker-bake.ci.hcl
          load: false
          push: false